spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EquipmentInventory
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  flyway:
    baseline-on-migrate: true
