spring:
  datasource:
    url: jdbc:postgresql://34.118.103.195:5432/postgres
    username: postgres
    password: DA5CK5ZfQnxkiwo9mRaq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  flyway:
    baseline-on-migrate: true
myapp:
  secretKey: "46cf5776e9795db0e5606570207c667d282704912fd91352020c553b766a4d8c" 





